### ISSUE TITLE
Messages/Announcments API

### ISSUE THREAD

**Issue by chriswininger** [infinite-industries/infinite#138]
A way to control/turn on off the jumbotron message

**Comment by MatthewGidcomb** [comment]
Questions to answer regarding the frontend:

- What views do we want the jumbotron to appear over? Currently it's only on the home page because it was redundant on the `/remote` page and annoying in the admin portal. Could the message support some kind of "page scope" that specifies which pages to show or not show the message on?
- Should the jumbotron message support markup, and if so how will links be handled? Currently it's using a `nuxt-link` component to allow readers to navigate to the Remote page. We can support displaying arbitrary markup (if we're appropriately careful about the source of it) using `v-html`, but that can't be used to insert arbitrary components.
- Should the jumbotron always render on initial page load when there's an active message, or should there be an option to control its visibility if we can tell (via cookie or local storage value) that the user has already seen it?
