### ISSUE TITLE
Time is not entered correctly into db 

### ISSUE THREAD

**Issue by Digi-D** [infinite-industries/infinite#64]
Current format: [{"end_time": "2019-12-08T01:30:00.000Z", "start_time": "2019-12-08T00:00:00.000Z", "optional_title": ""}]

Correct format: [{"end_time": "2019-12-06 17:00:00", "start_time": "2019-12-06 16:00:00", "optional_title": ""}]

Need to investigate if this is happening at portal or api level.

**Comment by chriswininger** [comment]
been looking at this. I'm pretty sure this was intentional and goes back to this commit https://github.com/infinite-industries/infinite-old-api-server/commit/1f003054de041029bd1a513786bb9b0d0d609016

I am able to submit issues, they are persisted in the format 2019-12-08T01:30:00.000Z as expected and display in browser in EST as expected; so, I guess I need more information about what the exact bug is

**Comment by chriswininger** [comment]
I think if you drop the utc conversion and Z from the end of the dates like we used to do, then if someone is viewing the page in another timezone they will render wrong because the browser won't know what timezone to convert to EST from, that's why we made this change

**Comment by chriswininger** [comment]
This was about more than the date. Prod was hosting an old copy of the UI. I updated the nginx and killed the extra node process.
